-- 0023: RSC Ghana region — one hub per church, each with a login.
--
-- Reasonable Service Churches (RSC) is a Ghana denomination with 6 churches.
-- Per the user's instruction, RSC is the region and each church is a hub with
-- its own login (hub_identifier = 'name', so the password is the hub name,
-- changed on first login).
--
-- Pastor contact info (leader_name, leader_phone) is stored on hub_churches
-- for office reference only — it has nothing to do with the ingest/login flow.
--
-- Already applied to the live database via the REST API on 2026-10-07.
-- This migration documents the change so it's tracked in git and reproducible.

begin;

insert into public.regions (code, name, hub_identifier, sort_order)
values ('RSC_GHANA', 'RSC Ghana', 'name', 5)
on conflict (code) do nothing;

-- Each church becomes a hub. The region_id is resolved at insert time.
-- hub_number is NULL (named region, not numbered).
-- name_key is the uppercase single-spaced name used for uniqueness within the region.

insert into public.hubs (name, name_key, leader_name, country, region_id)
select
  v.name,
  upper(regexp_replace(trim(v.name), '\s+', ' ', 'g')),
  v.leader_name,
  'Ghana',
  (select id from public.regions where code = 'RSC_GHANA')
from (values
  ('The Mega Church - Grace Cathedral', 'Bishop Patrick Bruce'),
  ('The Mega Church - Nachal Cathedral', 'Bishop Nassib Hage'),
  ('Keep My Word Chapel Int', 'Bishop Emmanuel Nterful'),
  ('Anointed People Intenational', 'Bishop Edwin Ogoe'),
  ('Anointed Word Chapel', 'Bishop Eddy Addy'),
  ('Glory Hope Love Center', 'Bishop E.A.T Sackey')
) as v(name, leader_name)
on conflict do nothing;

-- One church per hub (the church = the hub for this denomination).
-- leader_phone is the pastor's WhatsApp number from the office CSV.

insert into public.hub_churches (hub_id, name, name_key, leader_name, leader_phone)
select
  h.id,
  h.name,
  h.name_key,
  h.leader_name,
  v.phone
from public.hubs h
join (values
  ('The Mega Church - Grace Cathedral', '0244608531'),
  ('The Mega Church - Nachal Cathedral', '0244414454'),
  ('Keep My Word Chapel Int', '0545990505'),
  ('Anointed People Intenational', '0244382007'),
  ('Anointed Word Chapel', '0244272898'),
  ('Glory Hope Love Center', '0599500003')
) as v(name, phone) on upper(regexp_replace(trim(v.name), '\s+', ' ', 'g')) = h.name_key
where h.region_id = (select id from public.regions where code = 'RSC_GHANA')
on conflict do nothing;

-- Hub accounts (logins). Initial password = hub name, must change on first login.
-- The password_hash is generated by the app's scrypt helper (src/lib/hub/password.ts).
-- Since we cannot compute scrypt hashes in SQL, the accounts were created via
-- the REST API. This migration documents them; if re-run on a fresh database,
-- the accounts must be created via the app's password hashing, not this SQL.
-- The insert below is intentionally skipped to avoid storing plaintext passwords.

-- (Accounts already exist on the live database, created via REST API with
--  scrypt-hashed passwords. See scripts/create-rsc-logins.ts for the script.)

commit;

-- Undo:
--   begin;
--   delete from public.hub_accounts
--     where hub_id in (select id from public.hubs where region_id = (select id from public.regions where code = 'RSC_GHANA'));
--   delete from public.hub_churches
--     where hub_id in (select id from public.hubs where region_id = (select id from public.regions where code = 'RSC_GHANA'));
--   delete from public.hubs where region_id = (select id from public.regions where code = 'RSC_GHANA');
--   delete from public.regions where code = 'RSC_GHANA';
--   commit;